version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: johandler_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: johandler_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: