version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DATABASE_URL: postgresql://postgres:lskA2Aslvbjyr$2sc@db.envebdanxsujiybzlxgw.supabase.co:5432/postgres?sslmode=require
      RUST_LOG: debug
    ports:
      - "5150:5150"
    volumes:
      - .:/usr/src/app
    command: cargo run --release --bin johandler-cli start