# fly.toml app configuration file generated for johandler on 2024-12-30T17:35:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "johandler"
primary_region = "gig"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2