//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub mod prelude;

pub mod clients;
pub mod fees;
pub mod order_fees;
pub mod orders;
pub mod partners;
pub mod payments;
pub mod postponed_payments;
pub mod processes;
pub mod sellers;
pub mod users;
