//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::clients::Entity as Clients;
pub use super::fees::Entity as Fees;
pub use super::order_fees::Entity as OrderFees;
pub use super::orders::Entity as Orders;
pub use super::partners::Entity as Partners;
pub use super::payments::Entity as Payments;
pub use super::postponed_payments::Entity as PostponedPayments;
pub use super::processes::Entity as Processes;
pub use super::sellers::Entity as Sellers;
pub use super::users::Entity as Users;
