name: CI and Deploy to Heroku

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  HEROKU_API_KEY: HRKU-f008c8b2-66d3-43cc-8322-d5a8b6e6150e
  HEROKU_APP_NAME: johandler-api

jobs:
  build:
    name: Build and Deploy to Heroku
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Heroku Container Registry
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web -f Dockerfile.app .

      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: Release the application
        run: |
          heroku container:release web --app ${{ env.HEROKU_APP_NAME }}